### PR TITLE
v1.8 - added the ability to launch applications in the background

### PR DESCRIPTION
**Pull request by Deridder45**

### CODE REVIEW

**Comment by Psychoboy** [comment]
This PR would be very handy to me personally.

**Comment by KuzonCode** [comment]
@BarRaider Any plans to review/merge this PR? Asking as I was thinking of writing a feature to allow for is the application is focused, minimise it. Basically toggle visibility.

**Comment by BarRaider** [comment]
No plans,
PR included way too much irrelevant code which complicated inserting it into the codebase. I'll try to extract the relevant parts in a future update.

**Comment by BarRaider** [comment]
I'll try to extract the relevant parts in a future update

**Comment by benwitman** [comment]
@BarRaider any updates here?  I would love this feature :-).

**Comment by dosoft** [comment]
Just a friendly reminder about integrating this patch which is definitely a must-have feature.

**Comment by jahands** [comment]
I would really love this!

**Comment by BarRaider** [comment]
Sorry for the delay, this is available in the Early Access version on our Discord.
https://buz.bz/d

Should be in next official release too

**Pull request closed without merging**
